#!/bin/bash

# import .env
set -o allexport; source .env; set +o allexport

# load access token from tokens.json
PAYCOR_ACCESS_TOKEN="$(jq -r '.access_token' .tokens.json)"

# execute request
curl \
  "https://${PAYCOR_API_HOST:-apis.paycor.com}/v1/legalentities/${PAYCOR_LEGAL_ENTITY_ID}/employees?include=All" \
  --header "accept: application/json" \
  --header "Authorization: Bearer ${PAYCOR_ACCESS_TOKEN}" \
  --header "Ocp-Apim-Subscription-Key: ${PAYCOR_API_SUBSCRIPTION_KEY}" \
  --fail \
  --silent \
  --show-error \
| jq -r '.records'

# NOTE: this only grabs the first page of records, adjacent to
# the `records` key are the keys `hasMoreResults` and
# `continuationToken` for fetching subsequent pages

# NOTE: there is also the /v1/tenants/{tenantId}/employees endpoint which
# seems to return the same record set with less detail and be an older endpoint,
# but there may be some reason to use it
